language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
sudo: false
branches:
  only:
  - master
cache: pip
env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.8
install:
  - pip install pytest-django
  - pip install psycopg2
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: pytest
