language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
sudo: false
cache: pip
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
install:
  - pip install pytest pytest-django
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: pytest
