language: python
python:
  - '3.4'
  - '3.5'
sudo: false
branches:
  only:
  - master
cache: pip
env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11a1
services: postgresql
addons:
  postgresql: '9.4'
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - psql -c "select version();" -U postgres
install:
  - pip install pytest-django
  - pip install psycopg2
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: pytest
